#!/bin/bash

[ "$UID" -eq 0 ] || exec sudo "$0" "$@"
binfolder=$(echo $PATH | cut -d ":" -f 1)
echo "Searching for bin folder..."
sleep 0.3
echo "Found folder: $binfolder"
echo "Moving..."
sleep 0.3
sudo cp progressbar $binfolder
echo "Done! now you can use the progress bar."
